# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAuth():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_auth(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1920, 961)
    self.driver.find_element(By.CSS_SELECTOR, ".auth").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "password").send_keys("123")
    self.driver.find_element(By.ID, "email").send_keys("kopylovnikita2004@gmail.com")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "body > button").click()
    self.driver.find_element(By.LINK_TEXT, "Admin panel").click()
    self.driver.find_element(By.LINK_TEXT, "Post").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .icon > .fa").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Post 123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, "tbody > tr:nth-child(1) > .col-title").click()
  
